const ACTIONS = {
  JOIN: "JOIN",
  JOINED: "JOINED",
  DISCONNECTED: "DISCONNECTED",
  CODE_CHANGE: "CODE_CHANGE",
  SYNC_CODE: "SYNC_CODE",
  SEND_MESSAGE: "SEND_MESSAGE",
  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
  CURSOR_POSITION: "CURSOR_POSITION",
  CURSOR_UPDATE: "CURSOR_UPDATE",
};

module.exports = ACTIONS;